version: '3'


services:
    app:
      build: 
        context: .
      container_name: next-js-ui
      ports:
        - "3000:3000"  
        - "3001:3001"
      restart: always  
      stdin_open: true
      tty: true
      environment:
        NODE_ENV: development
      depends_on: 
        - database
      networks:
        - next-js-network   
    database:
      image: postgres:latest
      container_name: postgres-db
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD  
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5430:5432"  
      volumes:
        - ./../postgres-data:/var/lib/postgresql/data
      networks:
        - next-js-network 

networks:
  next-js-network:
    driver: bridge  


